/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LineageRouteImport } from './routes/lineage'
import { Route as DataStoreRouteImport } from './routes/data-store'
import { Route as ConfigureRouteImport } from './routes/configure'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataStoreIndexRouteImport } from './routes/data-store.index'
import { Route as DataStoreTableRouteImport } from './routes/data-store.table'

const LineageRoute = LineageRouteImport.update({
  id: '/lineage',
  path: '/lineage',
  getParentRoute: () => rootRouteImport,
} as any)
const DataStoreRoute = DataStoreRouteImport.update({
  id: '/data-store',
  path: '/data-store',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureRoute = ConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataStoreIndexRoute = DataStoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DataStoreRoute,
} as any)
const DataStoreTableRoute = DataStoreTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => DataStoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configure': typeof ConfigureRoute
  '/data-store': typeof DataStoreRouteWithChildren
  '/lineage': typeof LineageRoute
  '/data-store/table': typeof DataStoreTableRoute
  '/data-store/': typeof DataStoreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configure': typeof ConfigureRoute
  '/lineage': typeof LineageRoute
  '/data-store/table': typeof DataStoreTableRoute
  '/data-store': typeof DataStoreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configure': typeof ConfigureRoute
  '/data-store': typeof DataStoreRouteWithChildren
  '/lineage': typeof LineageRoute
  '/data-store/table': typeof DataStoreTableRoute
  '/data-store/': typeof DataStoreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configure'
    | '/data-store'
    | '/lineage'
    | '/data-store/table'
    | '/data-store/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configure'
    | '/lineage'
    | '/data-store/table'
    | '/data-store'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/configure'
    | '/data-store'
    | '/lineage'
    | '/data-store/table'
    | '/data-store/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConfigureRoute: typeof ConfigureRoute
  DataStoreRoute: typeof DataStoreRouteWithChildren
  LineageRoute: typeof LineageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lineage': {
      id: '/lineage'
      path: '/lineage'
      fullPath: '/lineage'
      preLoaderRoute: typeof LineageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-store': {
      id: '/data-store'
      path: '/data-store'
      fullPath: '/data-store'
      preLoaderRoute: typeof DataStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-store/': {
      id: '/data-store/'
      path: '/'
      fullPath: '/data-store/'
      preLoaderRoute: typeof DataStoreIndexRouteImport
      parentRoute: typeof DataStoreRoute
    }
    '/data-store/table': {
      id: '/data-store/table'
      path: '/table'
      fullPath: '/data-store/table'
      preLoaderRoute: typeof DataStoreTableRouteImport
      parentRoute: typeof DataStoreRoute
    }
  }
}

interface DataStoreRouteChildren {
  DataStoreTableRoute: typeof DataStoreTableRoute
  DataStoreIndexRoute: typeof DataStoreIndexRoute
}

const DataStoreRouteChildren: DataStoreRouteChildren = {
  DataStoreTableRoute: DataStoreTableRoute,
  DataStoreIndexRoute: DataStoreIndexRoute,
}

const DataStoreRouteWithChildren = DataStoreRoute._addFileChildren(
  DataStoreRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConfigureRoute: ConfigureRoute,
  DataStoreRoute: DataStoreRouteWithChildren,
  LineageRoute: LineageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
